"""Added initial table 3 

Revision ID: 30d1ce9e1cf0
Revises: 4b4d8619fc61
Create Date: 2023-11-08 14:03:28.986289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d1ce9e1cf0'
down_revision = '4b4d8619fc61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
