"""second

Revision ID: 7e7bf50bf95a
Revises: 6ade8e56106e
Create Date: 2023-11-09 13:59:18.431053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7bf50bf95a'
down_revision = '6ade8e56106e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
