"""third-verion

Revision ID: f6aa2e35a59b
Revises: 7e7bf50bf95a
Create Date: 2023-11-09 14:16:27.867508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6aa2e35a59b'
down_revision = '7e7bf50bf95a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
